# Generated by Django 4.0.3 on 2022-06-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('cant_view_profile', 'cant view profile')]},
        ),
    ]
