# Generated by Django 4.0.3 on 2022-06-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('comment_pics', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('comment_date_created', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_author', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('reply_pics', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reply_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_author', to='profiles.profile')),
                ('reply_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='hometweet.coment')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactions', models.CharField(choices=[('like', 'like'), ('love', 'love'), ('angry', 'angry'), ('care', 'care'), ('wow', 'wow'), ('sad', 'sad')], max_length=50)),
                ('Reaction_coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coment', to='hometweet.coment')),
                ('Reaction_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='hometweet.post')),
                ('Reaction_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_reply', to='hometweet.reply')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='coment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='hometweet.post'),
        ),
    ]
