# Generated by Django 4.0.3 on 2022-06-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hometweet', '0002_alter_reaction_reaction_coment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='Reaction_coment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coment', to='hometweet.coment'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='Reaction_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_reply', to='hometweet.reply'),
        ),
    ]
