# Generated by Django 4.0.3 on 2022-06-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=100)),
                ('videos', models.FileField(blank=True, null=True, upload_to='media/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.TextField(blank=True, null=True)),
                ('admin', models.ManyToManyField(related_name='admin', to='profiles.profile')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='group', to='auth.group')),
                ('members', models.ManyToManyField(related_name='members', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupappRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accept', 'accept'), ('send', 'send')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('groupapp', models.ManyToManyField(related_name='groupapps', to='groupapp.groupapp')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupreceivers', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsenders', to='profiles.profile')),
            ],
        ),
    ]
